//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi02
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialList
    {
        public int IdList { get; set; }
        public Nullable<int> ReqId { get; set; }
        public Nullable<int> MaterId { get; set; }
        public Nullable<int> AmountInList { get; set; }
        [JsonIgnore]
        public virtual Quire Quire { get; set; }
        [JsonIgnore]
        public virtual Storage Storage { get; set; }
    }
}
