//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi02
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Quire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quire()
        {
            this.MaterialList = new HashSet<MaterialList>();
        }
    
        public int IdQuire { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SpecId { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Theme { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Status { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<MaterialList> MaterialList { get; set; }
        [JsonIgnore]
        public virtual Users Users { get; set; }
        [JsonIgnore]
        public virtual Spec Spec { get; set; }
    }
}
